"""Programmatic number injection.

Prose is composed over the returned rows with every figure substituted in from
the result set by code — never generated by a model. Hallucinated numbers are
structurally impossible, not merely discouraged. (An LLM-narration variant could
replace the templating, but it would still receive numbers only as code-filled
slots — the guarantee is the injection, not the templating.)
"""

from __future__ import annotations

from peerlens.agent import catalog
from peerlens.agent.execute import Execution
from peerlens.agent.plan import Intent, ResolvedPlan


def _fmt(value: float | None, metric: str) -> str:
    if value is None:
        return "no data"
    spec = catalog.METRICS[metric]
    if spec.unit == "rate":
        return f"{value:.1%}"
    if spec.unit == "usd":
        return f"${value:,.0f}"
    return f"{value:,.0f}"


def render_answer(plan: ResolvedPlan, execution: Execution) -> str:
    """Compose the answer text; all numbers come from ``execution.rows``."""
    spec = catalog.METRICS[plan.metric]
    year = plan.years[0]
    by_id = {int(r["unitid"]): r for r in execution.rows}
    target = by_id.get(plan.target_unitid)
    if target is None:
        return f"No {spec.label.lower()} data for {plan.target_name} in {year}."

    target_val = target["metric_value"]
    head = f"{plan.target_name}'s {spec.label.lower()} was {_fmt(target_val, plan.metric)} in {year}."

    if plan.intent == Intent.SINGLE or len(execution.rows) <= 1:
        return head

    others = [r for r in execution.rows if int(r["unitid"]) != plan.target_unitid]
    valued = [r for r in execution.rows if r["metric_value"] is not None]
    ranked = sorted(valued, key=lambda r: r["metric_value"], reverse=True)
    rank = next((i + 1 for i, r in enumerate(ranked) if int(r["unitid"]) == plan.target_unitid), None)

    parts = [head]
    if rank is not None:
        parts.append(f"That ranks {rank} of {len(ranked)} in the compared set.")
    if others:
        top = ranked[0]
        bot = ranked[-1]
        parts.append(
            f"Highest: {top['inst_name']} ({_fmt(top['metric_value'], plan.metric)}); "
            f"lowest: {bot['inst_name']} ({_fmt(bot['metric_value'], plan.metric)})."
        )
    return " ".join(parts)
